rvm:
 - 2.3
 - 2.4
 - 2.5

script: 'bundle exec rspec spec'
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile

# Move to containerized travis, see http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false
cache: bundler
